// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LikeController from "./like_controller"
application.register("like", LikeController)

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import PdfGenerateController from "./pdfGenerate_controller"
application.register("pdfGenerate", PdfGenerateController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)

import ProfileStepController from "./profileStep_controller"
application.register("profileStep", ProfileStepController)

import ResumeController from "./resume_controller"
application.register("resume", ResumeController)

import SlimselectController from "./slimselect_controller"
application.register("slimselect", SlimselectController)
