# .rubocop.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    
Style/SingleLineMethods:
    Enabled: false

Layout/LineLength:
  Max: 100

Style/Encoding:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/HashSyntax:
  Enabled: false

